Collapsable subassets for a grail card
jdogresorg/freewallet-desktop pull request #91
Opened 2022-04-10 09:30 UTC by mariodian

A better way to list sub-assets that belong to a grail card. Sub-assets that do have a grail will be hidden by default. See the screenshot:

![Screen Shot 2022-04-10 at 4 56 58 PM](https://user-images.githubusercontent.com/3636406/162611747-7ce3fdb5-8ea8-4a0f-94f7-2508c527e825.png)

The reasoning behind this change is to save space in the "balances" list. This became an issue especially with some of the sub-asset heavy projects like PHOCKHEADS.

2022-04-20 16:55 UTC, jdogresorg commented
Overall the code looks decent (haven't had a chance to test it yet), but I would prefer it if you could update the code to stop referring to the parent asset as the "grail" card and refer to it as the parent asset, since it is easier to understand the parent-child subasset relationship than it is to understand what a "grail card" is.

Please change any reference to "grail" to be "parent" or "parent_asset"... this will make the code easier to understand what is going on... just a personal preference.

Once this update is made i'll spend some time testing this update and get it merged into the next release if all looks good.

Thanks for this PR... seems like cool functionality that will enhance the wallet a bit :)

2022-04-20 16:56 UTC, jdogresorg requested changes
please replace any "grail" reference with either "parent" or "parent_asset" to make the code a bit easier to follow (grail card is not universally understood as a parent asset)

2022-04-22 09:23 UTC, mariodian commented
Thanks for the feedback. I will look into it, however I'm gonna travel extensively in the next coming months, so it may take a while.

2022-04-26 19:30 UTC, merged

2022-10-11 06:53 UTC, jdogresorg commented
No worries, I can merge and tweak the variable name when the time comes if it’s not already done😀👍🏻

Sent from my iPhone

> On Apr 22, 2022, at 2:23 AM, Mario Dian ***@***.***> wrote:
> 
> ﻿
> Thanks for the feedback. I will look into it, however I'm gonna travel extensively in the next coming months, so it may take a while.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.